Escaping script tag on create and comment ticket.
BadChoice/handesk pull request #615
Opened 2021-01-05 12:40 UTC by aleixgil

Example: <script>alert(1)</script> => result: <\script>alert(1)</\script>.

Tests made:
 - can_create_a_ticket_with_js_injection()
 - requester_can_comment_the_ticket_with_js_injection()

2021-01-06 16:16 UTC, BadChoice requested changes

2021-01-06 16:16 UTC, BadChoice commented on helpers/helpers.php
> +    return str_replace('/script>', '/\script>', str_replace('<script', '<\script', $text));
diria que es pot fer mes facil amb el htmlentities o el htmlspecialchars

https://stackoverflow.com/questions/5986972/php-xss-sanitization

2021-01-06 16:17 UTC, BadChoice commented on helpers/helpers.php
> +    return str_replace('/script>', '/\script>', str_replace('<script', '<\script', $text));
o el strip_tags

2021-01-06 16:17 UTC, BadChoice commented on helpers/helpers.php
> +    return str_replace('/script>', '/\script>', str_replace('<script', '<\script', $text));
https://www.cloudways.com/blog/prevent-xss-exploits-using-laravel-validation-and-sanitization/

2021-01-07 08:27 UTC, aleixgil commented on helpers/helpers.php
> +    return str_replace('/script>', '/\script>', str_replace('<script', '<\script', $text));
Cert, he utilitzat el strip_tags. 👍🏽

2021-01-11 16:22 UTC, BadChoice approved these changes

2021-01-11 16:22 UTC, merged